version: '3'
services:
  php:
    build:
      context: ./php
    volumes:
      - ./code:/var/www/html
    ports:
      - "8000:80"
    depends_on:
      - mysql
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./code:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
  mysql:
    build: ./mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: dev_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 13314:3306
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
    networks:
      - app-network
  my_redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    networks:
      - app-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql:db
    ports:
      - 4000:80
    volumes:
      - ./phpmyadmin/sessions:/sessions
    networks:
      - app-network
networks:
  app-network:
    external: true